Exercise2MVC/Models/Entities/Parcel.cs
using Exercise2MVC.Helpers;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Exercise2MVC.Models.Entities
{
    [Table("Parcels")]
    public class Parcel
    {
        public int ParcelID { get; set; }

        public int CustomerID { get; set; }

        [Required(ErrorMessage = "Title is mandatory")]
        [AppValidator(ErrorMessage = "Title must be unique.")]
        public string Title { get; set; }

        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public virtual Customer Customer { get; set; }
        public virtual ICollection<ParcelItem> ParcelItems { get; set; }
    }
}

Exercise2MVC/Controllers/ParcelController.cs
using Exercise2MVC.Contracts.Services;
using Exercise2MVC.DataAccess.Repository;
using Exercise2MVC.Models.Entities;
using Exercise2MVC.Services;
using System.Web.Mvc;

namespace Exercise2MVC.Controllers
{
    public class ParcelController : Controller
    {
        private IParcelService _parcelService;

        private void InitDependency()
        {
            var repo = new ParcelRepository();
            _parcelService = new ParcelService(repo);
        }

        // GET: Parcel
        public ActionResult Index(int? customerId, int? page)
        {
            if (customerId == null)
            {
                return RedirectToAction("Index", "Customer");
            }

            InitDependency();

            var parcels = _parcelService.GetPagedParcels(customerId, page);

            TempData["customerId"] = customerId;

            return View(parcels);
        }

        // GET: Parcel/Create
        public ActionResult Create(int? customerId)
        {
            if (customerId == null)
            {
                return RedirectToAction("Index", "Customer");
            }

            return View(new Parcel() { CustomerID = (int)customerId });
        }

        // POST: Parcel/Create
        [HttpPost]
        public ActionResult Create(Parcel parcel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    InitDependency();

                    _parcelService.AddParcel(parcel);

                    TempData["SuccessMessage"] = $"Parcel added successfully.";

                    return RedirectToAction("Index", new {customerId = parcel.CustomerID});
                }
            }
            catch
            {
                return View("Error", "_Layout");
            }

            return View(parcel);
        }

        // GET: Parcel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Customer");
            }

            InitDependency();

            Parcel parcel = _parcelService.GetParcelById(id);

            if (parcel == null)
            {
                TempData["ErrorMessage"] = "Parcel not found.";
                return RedirectToAction("Index");
            }

            return View(parcel);
        }

        // POST: Parcel/Edit/5
        [HttpPost]
        public ActionResult Edit(Parcel parcel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    InitDependency();

                    _parcelService.UpdateParcel(parcel);

                    TempData["SuccessMessage"] = $"Parcel updated successfully.";

                    return RedirectToAction("Index", new { customerId = parcel.CustomerID} );
                }
            }
            catch
            {
                return View("Error", "_Layout");
            }

            return View(parcel);
        }

        // GET: Parcel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Customer");
            }

            InitDependency();

            Parcel parcel = _parcelService.GetParcelById(id);

            if (parcel == null)
            {
                TempData["ErrorMessage"] = "Parcel not found.";
                return RedirectToAction("Index");
            }

            return View(parcel);
        }

        // POST: Parcel/Delete/5
        [HttpPost, ActionName("DeleteConfirmed")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                InitDependency();

                Parcel parcel = _parcelService.DeleteParcelAndRelatedData(id);

                TempData["SuccessMessage"] = $"Parce {parcel.Title} deleted successfully.";

                return RedirectToAction("Index", new { customerId = parcel.CustomerID });
            }
            catch
            {
                return View("Error", "_Layout");
            }
        }
    }
}

Exercise2MVC/Controllers/ParcelItemController.cs
using Exercise2MVC.Contracts.Services;
using Exercise2MVC.DataAccess.Repository;
using Exercise2MVC.Models.Entities;
using Exercise2MVC.Services;
using System.Web.Mvc;

namespace Exercise2MVC.Controllers
{
    public class ParcelItemController : Controller
    {
        private IParcelItemService _parcelItemService;

        private void InitDependency()
        {
            var repo = new ParcelItemRepository();
            _parcelItemService = new ParcelItemService(repo);
        }

        // GET: ParcelItem
        public ActionResult Index(int? parcelId, int? page)
        {
            if (parcelId == null)
            {
                return RedirectToAction("Index","Customer");
            }

            InitDependency();

            var parcel = _parcelItemService.GetParcelById(parcelId);
            var parcelItems = _parcelItemService.GetPagedParcelItems(parcelId, page);

            TempData["parcelId"] = parcelId;
            TempData["customerId"] = parcel.CustomerID;

            return View(parcelItems);
        }

        // GET: ParcelItem/Create
        public ActionResult Create(int? parcelId)
        {
            if (parcelId == null)
            {
                return RedirectToAction("Index", "Customer");
            }

            ParcelItem parcelItem = new ParcelItem
            {
                Parcel = new Parcel { ParcelID = (int)parcelId },
                ParcelID = (int)parcelId
            };

            return View(parcelItem);
        }

        // POST: ParcelItem/Create
        [HttpPost]
        public ActionResult Create(ParcelItem parcelItem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    InitDependency();

                    _parcelItemService.AddParcelItem(parcelItem);

                    TempData["SuccessMessage"] = $"Parcel Item added successfully.";

                    return RedirectToAction("Index", new { parcelId = parcelItem.ParcelID });
                }
            }
            catch
            {
                return View("Error", "_Layout");
            }

            parcelItem = new ParcelItem
            {
                Parcel = new Parcel { ParcelID = parcelItem.ParcelID },
                ParcelID = parcelItem.ParcelID
            };

            return View(parcelItem);
        }

        // GET: ParcelItem/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Customer");
            }

            InitDependency();

            ParcelItem parcel = _parcelItemService.GetParcelItemById(id);

            TempData["customerId"] = parcel.Parcel.CustomerID;

            if (parcel == null)
            {
                TempData["ErrorMessage"] = "Parcel not found.";
                return RedirectToAction("Index");
            }

            return View(parcel);
        }

        // POST: ParcelItem/Edit/5
        [HttpPost]
        public ActionResult Edit(ParcelItem parcelIitem)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    InitDependency();

                    _parcelItemService.UpdateParcelItem(parcelIitem);

                    TempData["SuccessMessage"] = $"Parcel Item updated successfully.";

                    return RedirectToAction("Index", new { parcelId = parcelIitem.ParcelID });
                }
            }
            catch
            {
                return View("Error", "_Layout");
            }

            return View(parcelIitem);
        }

        // GET: ParcelItem/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Customer");
            }

            InitDependency();

            ParcelItem parcelItem = _parcelItemService.GetParcelItemById(id);

            if (parcelItem == null)
            {
                TempData["ErrorMessage"] = "Parcel Item not found.";
                return RedirectToAction("Index");
            }

            return View(parcelItem);
        }

        // POST: ParcelItem/Delete/5
        [HttpPost, ActionName("DeleteConfirmed")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                InitDependency();

                ParcelItem parcelItem = _parcelItemService.DeleteParcelItem(id);

                TempData["SuccessMessage"] = $"Parcel Item {parcelItem.Title} deleted successfully.";

                return RedirectToAction("Index", new { parcelId = parcelItem.ParcelID });
            }
            catch
            {
                return View("Error", "_Layout");
            }
        }
    }
}

Exercise2MVC/Views/Parcel/Create.cshtml
@model Exercise2MVC.Models.Entities.Parcel

@{
    ViewBag.Title = "Create";
}

<ul class="breadcrumb">
    <li>
        <a href="@Url.Action("Index", "Customer")">
            Customers
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Parcel", new { customerId = Model.CustomerID })">
            Parcels
        </a>
    </li>
    <li class="active">Add Parcel</li>
</ul>
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            @using (Html.BeginForm())
            {
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Parcel</h4>
                    </div>
                    <div class="modal-body text-center">
                        @Html.ValidationSummary(true)

                        <div class="form-group text-left">
                            <label for="Title"><span class="text-danger">*</span> Title:</label>
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Title, null, new { @class = "text-danger mt-3" })
                        </div>

                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" value="Create" class="btn btn-default">
                                    <i class="fa fa-save"></i> Save
                                </button>
                                <a href="@Url.Action("Index", "Parcel", new { customerId = Model.CustomerID })" class="btn btn-default">
                                    <i class="fa fa-minus-circle"></i> Cancel
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Exercise2MVC/Views/Parcel/Delete.cshtml
@model Exercise2MVC.Models.Entities.Parcel

@{
    ViewBag.Title = "Delete";
}

<ul class="breadcrumb">
    <li>
        <a href="@Url.Action("Index", "Customer")">
            Customers
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Parcel", new { customerId = Model.CustomerID })">
            Parcels
        </a>
    </li>
    <li class="active">Delete Parcel</li>
</ul>
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete Parcel</h4>
                </div>
                <div class="modal-body text-center">
                    <p>Are you sure you want to delete this parcel?</p>
                    <dl class="dl-horizontal">
                        <dt>Title:</dt>
                        <dd>@Model.Title</dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    @using (Html.BeginForm("DeleteConfirmed", "Parcel", new { id = Model.ParcelID }, FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-default">
                                    <i class="fa fa-trash"></i> Delete
                                </button>
                                <a href="@Url.Action("Index", "Parcel", new { customerId = Model.ParcelID })" class="btn btn-default">
                                    <i class="fa fa-minus-circle"></i> Cancel
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Exercise2MVC/Views/Parcel/Edit.cshtml
@model Exercise2MVC.Models.Entities.Parcel

@{
    ViewBag.Title = "Edit";
}

<ul class="breadcrumb">
    <li>
        <a href="@Url.Action("Index", "Customer")">
            Customers
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index", "Parcel", new { customerId = Model.CustomerID })">
            Parcels
        </a>
    </li>
    <li class="active">Update Parcel Info</li>
</ul>
<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            @using (Html.BeginForm())
            {
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Parcel</h4>
                    </div>
                    <div class="modal-body text-center">
                        @Html.ValidationSummary(true)
                        <input type="hidden" name="CustomerID" value="@Model.CustomerID" />
                        <input type="hidden" name="ParcelID" value="@Model.ParcelID" />
                        <div class="form-group text-left">
                            <label for="Title"><span class="text-danger">*</span> Title:</label>
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Title, null, new { @class = "text-danger mt-3" })
                        </div>

                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" value="Create" class="btn btn-default">
                                    <i class="fa fa-save"></i> Save
                                </button>
                                <a href="@Url.Action("Index", "Parcel", new { customerId = Model.CustomerID })" class="btn btn-default">
                                    <i class="fa fa-minus-circle"></i> Cancel
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Exercise2MVC/Views/Parcel/Index.cshtml
@using PagedList
@using PagedList.Mvc
@using Exercise2MVC.Helpers
@model IPagedList<Exercise2MVC.Models.Entities.Parcel>

@{
    ViewBag.Title = "Parcels";
}

<ul class="breadcrumb">
    <li>
        <a href="@Url.Action("Index", "Customer")">
            Customers
        </a>
    </li>
    <li class="active">Parcels</li>
</ul>

<div class="row" id="parcel-list">
    <div class="container">
        <h2 class="text-center">Parcels</h2>

        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger alert-dismissible fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Error!</strong> @TempData["ErrorMessage"]
            </div>
        }

        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success alert-dismissible fade in">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Success!</strong> @TempData["SuccessMessage"]
            </div>
        }

        <!-- Create Button -->
    <div class="text-right">
        <a href="@Url.Action("Create", "Parcel", new { customerId = TempData["customerId"]})" class="btn btn-default">
            <i class="fa fa-plus-circle"></i> Add Parcel
        </a>
    </div>

        <div class="table-responsive mb-5">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Delivery Classification</th>
                        <th>Total Weight</th>
                        <th>Total Cost</th>
                        <th>Created Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var parcel in Model)
                    {
                        decimal totalWeight = @parcel.ParcelItems.Select(s => s.Weight).Sum();

                        var deliveryInfo = ParcelCalculator.CalculateClassificationAndTotalCost(parcel.ParcelItems.ToList());

                        <tr>
                            <td>@parcel.Title</td>
                            <td>@deliveryInfo.Classification</td>
                            <td>@totalWeight</td>
                            <td>@string.Format("${0:N2}", deliveryInfo.Cost)</td>
                            <td>@parcel.CreatedDate.ToShortDateString()</td>
                            <td>
                                <a href="@Url.Action("Index", "ParcelItem", new { parcelId = parcel.ParcelID } )">
                                    <i class="fa fa-eye text-info"></i> View Parcel Items
                                </a> |
                                <a href="@Url.Action("Edit", "Parcel", new { id = parcel.ParcelID } )">
                                    <i class="fa fa-user text-success"></i> Edit
                                </a> |
                                <a href="@Url.Action("Delete", "Parcel", new { id = parcel.ParcelID } )">
                                    <i class="fa fa-trash text-danger"></i> Delete
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @if (Model.Any())
        {
            <div class="text-center">
                @Html.PagedListPager(Model, page => Url.Action("Index", new {customerId = Model.Select(s => s.CustomerID).FirstOrDefault(), page }), new PagedListRenderOptions { Display = PagedListDisplayMode.Always, MaximumPageNumbersToDisplay = 5 })
            </div>
        }

        @if (Model == null || !Model.Any())
        {
            <div class="text-center">
                <span>No Data Found.</span>
            </div>
        }
    </div>
</div>